version: '3.8'

services:
  meuDB:
    image: jgmatosmota/sql-hemera-tech:latest
    container_name: meuDB
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: meuDB
      MYSQL_USER: meuDB
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    mem_limit: 1g